apiVersion: v1
kind: Pod
metadata:
  name: ghost
  labels:
    app: ghost
spec:
  containers:
  - image: ghost
    name: ghost
    ports:
    - containerPort: 2368
      name: http
      protocol: TCP
